<?php
/**
 * Solucionador - exportacion JSON de resultados.
 */

defined('ABSPATH') || exit;

final class SEO_Solucionador_Export {
    const SCHEMA = 'seo-solucionador-export-v6';

    public static function init() {
        add_action('admin_post_seo_solucionador_export_json', array(__CLASS__, 'download'));
        add_action('admin_post_seo_solucionador_export_report_json', array(__CLASS__, 'download_simple_report'));
    }

    public static function download() {
        if (!current_user_can('manage_options')) {
            wp_die('No tienes permisos para exportar Solucionador.');
        }
        check_admin_referer('seo_solucionador_export_json');
        SEO_Solucionador_DB::maybe_install();
        $initialization = SEO_Solucionador_Engine::ensure_initialized(180);
        if (is_wp_error($initialization)) {
            wp_die(esc_html($initialization->get_error_message()));
        }

        $payload = self::build_payload();
        $json = wp_json_encode(
            $payload,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
        );
        if (!is_string($json)) {
            wp_die('No se pudo generar el JSON de Solucionador.');
        }

        while (ob_get_level() > 0) {
            @ob_end_clean();
        }

        $filename = sanitize_file_name('seo-solucionador-' . wp_date('Ymd-His') . '.json');
        nocache_headers();
        header('Content-Type: application/json; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('X-Content-Type-Options: nosniff');
        header('Content-Length: ' . strlen($json));
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Raw JSON download generated by wp_json_encode(); HTML escaping would corrupt the payload.
        echo $json;
        exit;
    }

    public static function download_simple_report() {
        if (!current_user_can('manage_options')) {
            wp_die('No tienes permisos para exportar Solucionador.');
        }
        check_admin_referer('seo_solucionador_export_report_json');
        SEO_Solucionador_DB::maybe_install();

        $payload = self::build_simple_report();
        $json = wp_json_encode(
            $payload,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
        );
        if (!is_string($json)) {
            wp_die('No se pudo generar el informe JSON de Solucionador.');
        }

        while (ob_get_level() > 0) {
            @ob_end_clean();
        }

        $filename = sanitize_file_name('solucionador-informe-' . wp_date('Ymd-His') . '.json');
        nocache_headers();
        header('Content-Type: application/json; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('X-Content-Type-Options: nosniff');
        header('Content-Length: ' . strlen($json));
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON generado por wp_json_encode().
        echo $json;
        exit;
    }

    public static function build_simple_report() {
        global $wpdb;

        $dossiers = SEO_Solucionador_DB::dossiers_table();
        $proposal_rows = SEO_Solucionador_DB::table_exists($dossiers)
            ? (array) $wpdb->get_results(
                "SELECT * FROM {$dossiers} WHERE question_count>0 ORDER BY category_name ASC,id ASC",
                ARRAY_A
            )
            : array();

        $posts = array();
        foreach ($proposal_rows as $dossier) {
            $category_id = absint($dossier['category_id'] ?? 0);
            if (!$category_id) continue;

            $key = 'dependiente-qa-basic|resolver|category-' . $category_id . '|general|general';
            $topic_id = SEO_Solucionador_DB::get_topic_id_by_key($key);
            $topic = $topic_id ? SEO_Solucionador_DB::get_topic($topic_id) : array();
            $title = trim((string) ($topic['suggested_title'] ?? ''));
            if ($title === '') {
                $title = trim((string) ($dossier['category_name'] ?? '')) . ': preguntas habituales, elección y uso';
            }

            $post_id = absint($topic['draft_post_id'] ?? 0);
            $post_status = $post_id ? (string) get_post_status($post_id) : '';
            $state = 'proposed';
            if ($post_status === 'publish') $state = 'published';
            elseif ($post_status && $post_status !== 'trash') $state = 'draft';
            elseif (sanitize_key((string) ($topic['workflow_state'] ?? '')) === 'rejected') $state = 'discarded';

            $items = array('faq'=>array(),'dependiente'=>array());
            foreach ((array)SEO_Solucionador_Dossiers::question_details($category_id) as $detail) {
                $question = trim((string)($detail['question'] ?? ''));
                $origin = sanitize_key((string)($detail['origin'] ?? 'dependiente'));
                if ($question === '' || !isset($items[$origin])) continue;
                $items[$origin][] = array(
                    'origin'=>$origin,
                    'source_id'=>$detail['source_id'] ?? null,
                    'item_key'=>(string)($detail['item_key'] ?? ''),
                    'question'=>$question,
                    'answer'=>SEO_Solucionador_Dossiers::answer_text((array)$detail),
                    'hash'=>(string)($detail['source_hash'] ?? ''),
                    'status'=>(string)($detail['editorial_state'] ?? 'unchanged'),
                    'editorial_choice'=>(string)($detail['editorial_choice'] ?? 'pending'),
                    'validation'=>(string)($detail['evaluation_status'] ?? ''),
                    'dependiente_source'=>(string)($detail['dependiente_source'] ?? ''),
                    'validated_at'=>(string)($detail['observed_at'] ?? ''),
                );
            }

            $posts[] = array(
                'category_id'=>$category_id,
                'category'=>(string)($dossier['category_name'] ?? ''),
                'faq_count'=>absint($dossier['faq_count'] ?? 0),
                'dependiente_count'=>absint($dossier['dependiente_count'] ?? 0),
                'title'=>$title,
                'state'=>$state,
                'wordpress_post_id'=>$post_id ?: null,
                'items'=>$items,
            );
        }

        $google = array();
        $meta_key = SEO_Solucionador_Posts::META_TOPIC_ID;
        $created_posts = (array) $wpdb->get_results(
            $wpdb->prepare(
                "SELECT DISTINCT p.ID,p.post_title,p.post_status
                 FROM {$wpdb->posts} p
                 INNER JOIN {$wpdb->postmeta} pm ON pm.post_id=p.ID
                 WHERE p.post_type='post' AND p.post_status<>'trash' AND pm.meta_key=%s
                 ORDER BY p.post_date DESC,p.ID DESC",
                $meta_key
            ),
            ARRAY_A
        );
        foreach ($created_posts as $row) {
            $post_id = absint($row['ID'] ?? 0);
            $metrics = function_exists('seo_post_reports_get_summary')
                ? (array) seo_post_reports_get_summary($post_id,28)
                : array();
            $google[] = array(
                'post_id'=>$post_id,
                'title'=>(string) ($row['post_title'] ?? ''),
                'status'=>(string) ($row['post_status'] ?? ''),
                'period_days'=>28,
                'has_snapshot'=>!empty($metrics['has_snapshot']),
                'impressions'=>absint($metrics['impressions'] ?? 0),
                'clicks'=>absint($metrics['clicks'] ?? 0),
                'pageviews'=>absint($metrics['pageviews'] ?? 0),
                'updated'=>absint($metrics['updated'] ?? 0),
            );
        }

        return array(
            'schema'=>'seo-solucionador-simple-v1',
            'generated_at'=>current_time('mysql'),
            'posts'=>$posts,
            'google'=>$google,
        );
    }

    public static function build_payload() {
        global $wpdb;

        $topics_table = SEO_Solucionador_DB::topics_table();
        $evidence_table = SEO_Solucionador_DB::evidence_table();
        $post_topics_table = SEO_Solucionador_DB::post_topics_table();
        $coverage_table = SEO_Solucionador_DB::coverage_table();
        $workflow_table = SEO_Solucionador_DB::workflow_table();
        $dossiers_table = SEO_Solucionador_DB::dossiers_table();

        $topics = SEO_Solucionador_DB::table_exists($topics_table)
            ? (array) $wpdb->get_results(
                "SELECT * FROM {$topics_table} ORDER BY priority_score DESC,evidence_total DESC,id ASC",
                ARRAY_A
            )
            : array();

        $evidence_rows = SEO_Solucionador_DB::table_exists($evidence_table)
            ? (array) $wpdb->get_results(
                "SELECT * FROM {$evidence_table} ORDER BY topic_id ASC,evidence_score DESC,occurrences DESC,id ASC",
                ARRAY_A
            )
            : array();

        $evidence_by_topic = array();
        foreach ($evidence_rows as $row) {
            $topic_id = absint($row['topic_id'] ?? 0);
            if (!$topic_id) continue;
            if (!isset($evidence_by_topic[$topic_id])) $evidence_by_topic[$topic_id] = array();
            $evidence_by_topic[$topic_id][] = self::normalize_evidence($row);
        }

        $topic_rows = array();
        foreach ($topics as $topic) {
            $topic_rows[] = self::normalize_topic(
                $topic,
                (array) ($evidence_by_topic[absint($topic['id'] ?? 0)] ?? array())
            );
        }

        $coverage_rows = array();
        if (SEO_Solucionador_DB::table_exists($coverage_table)) {
            $coverage_raw = (array) $wpdb->get_results(
                "SELECT * FROM {$coverage_table} ORDER BY entity_type,entity_id,scope,id ASC",
                ARRAY_A
            );
            foreach ($coverage_raw as $row) {
                $coverage_rows[] = self::normalize_coverage($row);
            }
        }

        $workflow_rows = SEO_Solucionador_DB::table_exists($workflow_table)
            ? (array) $wpdb->get_results("SELECT * FROM {$workflow_table} ORDER BY topic_id,id ASC",ARRAY_A)
            : array();

        $dossier_rows = SEO_Solucionador_DB::table_exists($dossiers_table)
            ? (array) $wpdb->get_results(
                "SELECT id,category_id,category_name,question_count,dependiente_count,faq_count,
                        question_ids,dependiente_keys,faq_ids,score_avg,last_validated_at,source_hash,
                        reviewed_hash,editorial_status,updated_at
                 FROM {$dossiers_table} ORDER BY category_name,id",
                ARRAY_A
            )
            : array();
        foreach ($dossier_rows as &$dossier_row) {
            $dossier_row['question_ids'] = SEO_Solucionador_DB::decode_json($dossier_row['question_ids'] ?? '[]',array());
            $dossier_row['dependiente_keys'] = SEO_Solucionador_DB::decode_json($dossier_row['dependiente_keys'] ?? '[]',array());
            $dossier_row['faq_ids'] = SEO_Solucionador_DB::decode_json($dossier_row['faq_ids'] ?? '[]',array());
            $dossier_row['origins'] = array(
                'dependiente'=>absint($dossier_row['dependiente_count'] ?? 0),
                'faq'=>absint($dossier_row['faq_count'] ?? 0),
            );

            $items = array('faq'=>array(),'dependiente'=>array());
            $category_id = absint($dossier_row['category_id'] ?? 0);
            if ($category_id && class_exists('SEO_Solucionador_Dossiers')) {
                foreach ((array)SEO_Solucionador_Dossiers::question_details($category_id) as $detail) {
                    $origin = sanitize_key((string)($detail['origin'] ?? 'dependiente'));
                    if (!isset($items[$origin])) continue;
                    $items[$origin][] = array(
                        'origin'=>$origin,
                        'source_id'=>$detail['source_id'] ?? null,
                        'item_id'=>(string)($detail['item_key'] ?? ''),
                        'product_id'=>absint($detail['product_id'] ?? 0) ?: null,
                        'question'=>(string)($detail['question'] ?? ''),
                        'answer'=>SEO_Solucionador_Dossiers::answer_text((array)$detail),
                        'hash'=>(string)($detail['source_hash'] ?? ''),
                        'status'=>(string)($detail['editorial_state'] ?? 'unchanged'),
                        'editorial_choice'=>(string)($detail['editorial_choice'] ?? 'pending'),
                        'validation'=>(string)($detail['evaluation_status'] ?? ''),
                        'question_type'=>(string)($detail['question_type'] ?? ''),
                        'lesson_key'=>(string)($detail['lesson_key'] ?? ''),
                        'dependiente_source'=>(string)($detail['dependiente_source'] ?? ''),
                        'confidence'=>(float)($detail['evaluation_score'] ?? 0),
                        'first_seen_at'=>(string)($detail['first_seen_at'] ?? ''),
                        'last_seen_at'=>(string)($detail['observed_at'] ?? ''),
                    );
                }
            }
            $changes = $category_id && method_exists('SEO_Solucionador_Dossiers','item_changes')
                ? SEO_Solucionador_Dossiers::item_changes($category_id)
                : array('new'=>array(),'modified'=>array(),'retired'=>array());
            $dossier_row['editorial_item_count'] = count($items['faq']) + count($items['dependiente']);
            $dossier_row['items'] = $items;
            $dossier_row['changes'] = array(
                'new'=>array_values((array)($changes['new'] ?? array())),
                'modified'=>array_values((array)($changes['modified'] ?? array())),
                'retired'=>array_values((array)($changes['retired'] ?? array())),
            );
            $dossier_row['note'] = 'Dos entradas independientes: FAQ humana + conocimiento real de Dependiente. No se deduplican destructivamente entre sí.';
        }
        unset($dossier_row);

        return array(
            'schema' => self::SCHEMA,
            'generated_at' => current_time('mysql'),
            'generated_at_gmt' => current_time('mysql', true),
            'site' => array(
                'home_url' => home_url('/'),
                'solucionador_version' => defined('SEO_SOLUCIONADOR_VERSION') ? SEO_SOLUCIONADOR_VERSION : '',
                'db_version' => (string) get_option(SEO_Solucionador_DB::VERSION_OPTION, ''),
            ),
            'last_scan' => (array) get_option('seo_solucionador_last_scan', array()),
            'sources' => class_exists('SEO_Solucionador_Dossiers') ? SEO_Solucionador_Dossiers::snapshot() : array(),
            // Alias 0.6 para consumidores existentes. En 0.7 el contenido ya es
            // mixto, por lo que los nuevos consumidores deben preferir "sources".
            'academy' => class_exists('SEO_Solucionador_Dossiers') ? SEO_Solucionador_Dossiers::snapshot() : array(),
            'summary' => self::summary($topics_table, $evidence_table, $coverage_table),
            'dossiers' => $dossier_rows,
            'topics' => $topic_rows,
            'editorial_coverage' => $coverage_rows,
            'workflow_history' => $workflow_rows,
            'measurement' => array(
                'source'=>'Analista',
                'note'=>'Los KPIs globales no se exportan desde la tabla histórica de tracking de Solucionador.',
            ),
        );
    }

    private static function normalize_topic(array $row, array $evidence) {
        $id = absint($row['id'] ?? 0);
        $existing_post_id = absint($row['existing_post_id'] ?? 0);
        $draft_post_id = absint($row['draft_post_id'] ?? 0);

        return array(
            'id' => $id,
            'canonical_key' => (string) ($row['canonical_key'] ?? ''),
            'canonical_question' => (string) ($row['canonical_question'] ?? ''),
            'profile' => array(
                'intent' => (string) ($row['intent'] ?? ''),
                'action' => (string) ($row['action_term'] ?? ''),
                'object' => (string) ($row['object_term'] ?? ''),
                'condition' => (string) ($row['condition_term'] ?? ''),
                'context' => (string) ($row['context_term'] ?? ''),
                'confidence' => (float) ($row['confidence'] ?? 0),
            ),
            'proposal' => array(
                'suggested_title' => (string) ($row['suggested_title'] ?? ''),
                'recommended_action' => (string) ($row['recommended_action'] ?? ''),
                'decision_reason' => (string) ($row['decision_reason'] ?? ''),
                'status' => (string) ($row['status'] ?? ''),
                'workflow_state' => (string) ($row['workflow_state'] ?? ''),
                'content_type' => (string) ($row['content_type'] ?? ''),
                'priority_score' => (float) ($row['priority_score'] ?? 0),
                'priority_components' => SEO_Solucionador_DB::priority_components($row),
                'requirements' => SEO_Solucionador_DB::decision_requirements($row),
                'vocabulary' => SEO_Solucionador_DB::proposed_vocabulary($row),
                'categories' => SEO_Solucionador_DB::proposed_categories($row),
                'primary_category_id' => absint($row['primary_category_id'] ?? 0),
                'hierarchy' => SEO_Solucionador_DB::hierarchy($row),
            ),
            'coverage' => array(
                'status' => (string) ($row['coverage_status'] ?? ''),
                'score' => (float) ($row['coverage_score'] ?? 0),
                'existing_entity_type' => (string) ($row['existing_entity_type'] ?? ''),
                'existing_entity_id' => absint($row['existing_entity_id'] ?? 0),
                'duplication_risk' => (float) ($row['duplication_risk'] ?? 0),
                'cannibalization_risk' => (float) ($row['cannibalization_risk'] ?? 0),
                'knowledge_status' => (string) ($row['knowledge_status'] ?? ''),
                'existing_post' => self::post_info($existing_post_id),
                'draft_post' => self::post_info($draft_post_id),
            ),
            'evidence_summary' => array(
                'total' => absint($row['evidence_total'] ?? 0),
                'dependiente_interprete' => absint($row['interpreter_evidence'] ?? 0),
                'comentarista' => absint($row['comentarista_evidence'] ?? 0),
                'analista' => absint($row['analyst_evidence'] ?? 0),
                'auditor' => absint($row['auditor_evidence'] ?? 0),
                'zero_results' => absint($row['zero_result_evidence'] ?? 0),
                'negative_feedback' => absint($row['negative_feedback_evidence'] ?? 0),
            ),
            'evidence' => $evidence,
            'dates' => array(
                'first_seen_at' => self::nullable_string($row['first_seen_at'] ?? null),
                'last_seen_at' => self::nullable_string($row['last_seen_at'] ?? null),
                'last_analyzed_at' => self::nullable_string($row['last_analyzed_at'] ?? null),
                'approved_at' => self::nullable_string($row['approved_at'] ?? null),
                'draft_created_at' => self::nullable_string($row['draft_created_at'] ?? null),
                'created_at' => self::nullable_string($row['created_at'] ?? null),
                'updated_at' => self::nullable_string($row['updated_at'] ?? null),
            ),
        );
    }

    private static function normalize_evidence(array $row) {
        return array(
            'id' => absint($row['id'] ?? 0),
            'source_type' => (string) ($row['source_type'] ?? ''),
            'source_id' => self::nullable_string($row['source_id'] ?? null),
            'signal_type' => (string) ($row['signal_type'] ?? ''),
            'entity_type' => (string) ($row['entity_type'] ?? ''),
            'entity_id' => absint($row['entity_id'] ?? 0),
            'category_id' => absint($row['category_id'] ?? 0),
            'source_text' => (string) ($row['source_text'] ?? ''),
            'source_meta' => SEO_Solucionador_DB::decode_json($row['source_meta'] ?? '', array()),
            'occurrences' => max(1, absint($row['occurrences'] ?? 1)),
            'confidence' => (float) ($row['confidence'] ?? 0),
            'evidence_score' => (float) ($row['evidence_score'] ?? 0),
            'observed_at' => self::nullable_string($row['observed_at'] ?? null),
            'created_at' => self::nullable_string($row['created_at'] ?? null),
        );
    }

    private static function normalize_coverage(array $row) {
        return array(
            'id' => absint($row['id'] ?? 0),
            'entity_type' => (string) ($row['entity_type'] ?? ''),
            'entity_id' => absint($row['entity_id'] ?? 0),
            'seo_role' => (string) ($row['seo_role'] ?? ''),
            'category_id' => absint($row['category_id'] ?? 0),
            'title' => (string) ($row['title'] ?? ''),
            'url' => (string) ($row['url'] ?? ''),
            'scope' => (string) ($row['scope'] ?? ''),
            'source_text' => (string) ($row['source_text'] ?? ''),
            'canonical_key' => (string) ($row['canonical_key'] ?? ''),
            'vocabulary_text' => (string) ($row['vocabulary_text'] ?? ''),
            'profile' => array(
                'intent' => (string) ($row['intent'] ?? ''),
                'action' => (string) ($row['action_term'] ?? ''),
                'object' => (string) ($row['object_term'] ?? ''),
                'condition' => (string) ($row['condition_term'] ?? ''),
                'context' => (string) ($row['context_term'] ?? ''),
                'confidence' => (float) ($row['confidence'] ?? 0),
            ),
            'updated_at' => self::nullable_string($row['updated_at'] ?? null),
        );
    }

    private static function post_info($post_id) {
        $post_id = absint($post_id);
        if (!$post_id) return null;
        $post = get_post($post_id);
        if (!$post) {
            return array('id' => $post_id, 'missing' => true);
        }
        return array(
            'id' => $post_id,
            'title' => (string) $post->post_title,
            'status' => (string) $post->post_status,
            'url' => (string) get_permalink($post_id),
            'edit_url' => (string) get_edit_post_link($post_id, 'raw'),
        );
    }

    private static function summary($topics_table, $evidence_table, $coverage_table) {
        global $wpdb;
        $summary = array(
            'topics_total' => 0,
            'evidence_occurrences_total' => 0,
            'editorial_coverage_rows' => 0,
            'by_status' => array(),
            'by_coverage' => array(),
            'by_recommended_action' => array(),
            'by_source' => array(),
        );

        if (SEO_Solucionador_DB::table_exists($topics_table)) {
            $summary['topics_total'] = absint($wpdb->get_var("SELECT COUNT(*) FROM {$topics_table}"));
            $summary['by_status'] = self::grouped_counts($topics_table, 'status');
            $summary['by_coverage'] = self::grouped_counts($topics_table, 'coverage_status');
            $summary['by_recommended_action'] = self::grouped_counts($topics_table, 'recommended_action');
        }

        if (SEO_Solucionador_DB::table_exists($evidence_table)) {
            $summary['evidence_occurrences_total'] = absint($wpdb->get_var("SELECT COALESCE(SUM(occurrences),0) FROM {$evidence_table}"));
            $rows = (array) $wpdb->get_results(
                "SELECT source_type,COALESCE(SUM(occurrences),0) total FROM {$evidence_table} GROUP BY source_type ORDER BY total DESC,source_type ASC",
                ARRAY_A
            );
            foreach ($rows as $row) {
                $summary['by_source'][(string) ($row['source_type'] ?? '')] = absint($row['total'] ?? 0);
            }
        }

        if (SEO_Solucionador_DB::table_exists($coverage_table)) {
            $summary['editorial_coverage_rows'] = absint($wpdb->get_var("SELECT COUNT(*) FROM {$coverage_table}"));
        }
        return $summary;
    }

    private static function grouped_counts($table, $column) {
        global $wpdb;
        $allowed = array('status', 'coverage_status', 'recommended_action');
        if (!in_array($column, $allowed, true)) return array();
        $rows = (array) $wpdb->get_results(
            "SELECT {$column} value,COUNT(*) total FROM {$table} GROUP BY {$column} ORDER BY total DESC,value ASC",
            ARRAY_A
        );
        $out = array();
        foreach ($rows as $row) {
            $out[(string) ($row['value'] ?? '')] = absint($row['total'] ?? 0);
        }
        return $out;
    }

    private static function nullable_string($value) {
        if ($value === null) return null;
        $value = trim((string) $value);
        return $value === '' ? null : $value;
    }
}
