name: Despliegue MAIN (staging) a producción (hosting)
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar versión de producción desde MAIN
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Subir SEO Taxonomy a producción por FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          port: 21

          local-dir: ./
          server-dir: ./

          dry-run: false
          security: strict

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/*.bak
            **/*.md
            **/*.pot
