      - name: Ver ruta del plugin
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -p 21 "$FTP_SERVER" <<'EOF'
          set cmd:fail-exit yes
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set ssl:verify-certificate yes

          echo "=== RAIZ ==="
          pwd
          cls -la

          echo "=== WP-CONTENT ==="
          cd wp-content
          pwd
          cls -la

          echo "=== PLUGINS ==="
          cd plugins
          pwd
          cls -la

          echo "=== SEO-TAXONOMY ==="
          cd seo-taxonomy
          pwd
          cls -la

          bye
          EOF
